[MOSIP-35101] created ansible script to provision RKE2 cluster, updated install nfs-csi config for default storage class and renamed istio install.yaml to sh
mosip/k8s-infra pull request #129
Opened 2024-08-27 11:20 UTC by bhumi46

2024-08-27 12:34 UTC, syedsalman3753 requested changes

2024-08-27 12:34 UTC, syedsalman3753 commented on k8-cluster/on-prem/rke2/ansible/README.md
> +    Update the `hosts.ini` file with your node details.
2. Update the `hosts.ini` file with your node details.

2024-08-27 12:34 UTC, syedsalman3753 commented on k8-cluster/on-prem/rke2/ansible/README.md
> +### Running the Playbook
Kubernetes setup via Ansible playbook

2024-08-27 13:20 UTC, bhumi46 commented on k8-cluster/on-prem/rke2/ansible/main.yaml
> +- import_playbook: playbook/subsequent-roles.yaml
it was already added in subsequent playbook, please check @syedsalman3753

2024-08-27 13:20 UTC, bhumi46 commented on k8-cluster/on-prem/rke2/ansible/README.md
> +Update the `hosts.ini` file with the correct IP addresses, usernames, and paths to your private key files.
updated

2024-08-27 13:21 UTC, bhumi46 commented on k8-cluster/on-prem/rke2/ansible/README.md
> +- **Supported OS:** Ubuntu or other Debian-based distributions.
updated

2024-08-29 12:53 UTC, ckm007 commented on k8-cluster/on-prem/rke2/ansible/README.md
> +This repository contains an Ansible playbook and associated configurations to set up an RKE2 Kubernetes cluster with a primary control plane, subsequent control plane nodes, agent nodes, and an etcd
please get Document approved by Keshav.

2024-08-29 13:28 UTC, ckm007 commented on k8-cluster/on-prem/rke2/ansible/README.md
> +- Ensure that nodes are accessible from your local machine for SSH authentication.
add playbook to check:
1. availability of ssh pem key to access all the required nodes.
2. performs the ssh connection and confirms the accesibility to the VM's.
3. presence of user with sudo priviledge in all the required instances.

2024-08-29 13:28 UTC, ckm007 commented on k8-cluster/on-prem/rke2/ansible/README.md
> +
follow .md .
add pointers *.

2024-08-29 13:28 UTC, ckm007 commented on k8-cluster/on-prem/rke2/ansible/README.md
> +# Primary control plane node. This is the main node where RKE2 will be installed first.
Dont display the contents of hosts.ini.
Rather make hosts.ini self explanatery.

Add comment to define the default roles for each type.

2024-08-29 13:28 UTC, ckm007 commented on k8-cluster/on-prem/rke2/ansible/README.md
> +- Update the `hosts.ini` file with the correct IP addresses, usernames, and paths to your private key files.
Update hosts.ini with required details.

2024-08-29 13:28 UTC, ckm007 commented on k8-cluster/on-prem/rke2/ansible/README.md
> +#### `main.yaml`
add playbook details in the README inside playbook directory which explains the usage deeply.

Here we should provide the detailed steps for                         Cluster creation , configuration etc.

2024-08-29 13:28 UTC, ckm007 commented on k8-cluster/on-prem/rke2/ansible/main.yaml
> +- import_playbook: playbook/subsequent-roles.yaml
playbook/primary-node.yaml

playbook/subsequent-node.yaml

2024-08-29 13:28 UTC, ckm007 commented on k8-cluster/on-prem/rke2/ansible/playbook/control-plane-primary.yaml
> +        executable: /bin/bash
add a task to copy the kubeconfig file into the existing directory of host from where ansible command was executed.

2024-08-29 13:28 UTC, ckm007 commented on k8-cluster/on-prem/rke2/ansible/ports.yaml
> +    # Nginx ingress controller (not sure if this is required)
add in document, for observation cluster creation uncomment this section.

2024-09-02 12:18 UTC, ckm007 commented on k8-cluster/on-prem/rke2/rke2-server-control-plane-primary.conf.template
>    - shouldInstallIstioIngress=true
Do we still need this label shouldInstallIstioIngress=true ?

2024-09-02 13:57 UTC, ckm007 approved these changes

2024-09-02 13:57 UTC, merged