[MOSIP-24294] fixed stable version of charts installed from Rancher Apps store
mosip/k8s-infra pull request #28
Opened 2022-10-18 10:44 UTC by gaganamadival

…pps store

2022-10-21 12:33 UTC, syedsalman3753 approved these changes

2022-10-21 12:33 UTC, syedsalman3753 commented on monitoring/README.md
> +4. Click on 'Install'.
Please make points as 1. for lines 6-11
markdown will set the sequence automatically

2022-10-21 16:41 UTC, ckm007 requested changes
Need document changes similar to one in monitoring for logging and longhorn readme.

2022-11-02 04:57 UTC, ckm007 approved these changes

2022-11-02 04:57 UTC, merged