Updated Localhost mapping script and info in k8s-infra.
mosip/k8s-infra pull request #34
Opened 2022-11-04 09:16 UTC by Mohanraj209

2022-11-07 05:58 UTC, syedsalman3753 commented
@Mohanraj209 please provide Ticket ID in the PR

2022-11-07 06:00 UTC, syedsalman3753 commented
Get the documentation review by @SwatiPeriwal

2022-11-07 06:23 UTC, SwatiPeriwal commented on mosip/on-prem/README.md
> +Below contains some of the information about localhost mapping in brief:
## Mapping localhost

2022-11-07 06:25 UTC, SwatiPeriwal commented on mosip/on-prem/README.md
> +Below contains some of the information about localhost mapping in brief:
Below is some information about localhost mapping in brief:

2022-11-07 06:28 UTC, SwatiPeriwal commented on mosip/on-prem/README.md
> +we faced an issue with nodal instances where we were getting issues as localhost mapping was not present in hosts file of the system.
An issue with the nodal instances was observed as localhost mapping was not present in the hosts file of the system.

2022-11-07 06:35 UTC, SwatiPeriwal commented on mosip/on-prem/README.md
> +Note: Because of the above issue for us to go and check manually in all the nodes of cluster it is vey tedious and time consuming task so we have written a ansible script and made it automation task.
Note: An ansible script was written and the task was automated to reduce the effort of checking all the nodes of the cluster. This was extremely tedious and time consuming manually.

2022-11-07 06:35 UTC, SwatiPeriwal commented on mosip/on-prem/README.md
> +* To check localhost mapping is present in all cluster nodes.
**To check localhost mapping is present in all cluster nodes**

2022-11-07 06:36 UTC, SwatiPeriwal commented on mosip/on-prem/README.md
> +* To view the ansible script or make any changes.
**To view the ansible script or make any changes**

2022-11-07 06:37 UTC, SwatiPeriwal commented on mosip/on-prem/README.md
> +Reason: This is because of localhost mapping i,e ```127.0.0.1    localhost``` might not being present within ```/etc/hosts``` file of the system.
Issue: Localhost mapping i.e. ```127.0.0.1    localhost``` might not being present within ```/etc/hosts``` file of the system.

2022-11-07 06:38 UTC, SwatiPeriwal commented on mosip/on-prem/README.md
> +Note: Because of the above issue for us to go and check manually in all the nodes of cluster it is vey tedious and time consuming task so we have written a ansible script and made it automation task.
Resolution: An ansible script was written and the task was automated to reduce the effort of checking all the nodes of the cluster. This was extremely tedious and time consuming manually.

2022-11-07 06:38 UTC, SwatiPeriwal requested changes
Added comments.. please verify and update changes accordingly.

2022-11-07 07:14 UTC, Mohanraj209 commented
@SwatiPeriwal mam i have made changes pls check once and approve it.

2022-11-07 08:33 UTC, SwatiPeriwal approved these changes
Approved changes..

2022-11-07 09:23 UTC, syedsalman3753 approved these changes

2022-11-22 03:55 UTC, ckm007 reviewed
# Mapping localhost changes defination should be added in troubleshooting docs.

2022-12-01 02:49 UTC, ckm007 approved these changes

2022-12-01 02:50 UTC, merged