[MOSIP-29901] updated the README.md for storage classed
mosip/k8s-infra pull request #75
Opened 2023-11-02 08:40 UTC by Rakshitha650

2023-11-02 10:53 UTC, syedsalman3753 approved these changes
approved

2023-11-02 13:16 UTC, ckm007 commented on mosip/aws/README.md
> +## The following storage classes can be used:
this is aw specific section.. here we should have gp2 or gp3 or EBS or EFS mentioned.

2023-11-02 13:17 UTC, ckm007 commented on mosip/on-prem/README.md
> +MOSIP is implementing `Longhorn` as its storage class solution for improved data management.
For time being considering Longhorn as a storage class.

2023-11-02 13:19 UTC, ckm007 commented
Did we add the same to reflect in our docs?

2023-11-07 13:55 UTC, SwatiPeriwal requested changes
please make the necessary changes and update

2023-11-08 05:12 UTC, SwatiPeriwal commented on mosip/on-prem/README.md
> +## The following storage classes can be used:
The heading cannot be a sentence.... You can have ## Storage Class and then write the sentence- The following storage classes can be used:

2023-11-08 05:13 UTC, SwatiPeriwal commented on mosip/on-prem/README.md
> +For time being considering Longhorn as a storage class.
For time being considering Longhorn as a storage class. - This sentence is incorrect... For time being. let us consider Longhorn as a storage class. 9or pls check the technical context and update accordingly

2023-11-08 05:14 UTC, SwatiPeriwal requested changes
Pls update the doc

2023-11-08 11:59 UTC, SwatiPeriwal approved these changes
Please capitalize S in the heading ## Storage Classes

2023-11-08 18:40 UTC, ckm007 approved these changes

2023-11-08 18:40 UTC, merged