[MOSIP-24203] Added documentation to back up & restore k8s cluster via ETCD
mosip/k8s-infra pull request #85
Opened 2024-02-01 15:47 UTC by syedsalman3753

2024-02-01 16:26 UTC, SwatiPeriwal commented on docs/etcd-backup-restore-via-rke.md
> +  * Once the restore operation successfully executed, Check the status of nodes, & pods of k8s cluster.
Once the restore operation is successfully executed, check the status of nodes and pods of k8s cluster.

2024-02-01 16:30 UTC, SwatiPeriwal commented on docs/etcd-backup-restore-via-rke.md
> +* To restore the state of the Kubernetes (k8s) cluster from a ETCD snapshot, execute the following command after updating the name of the snapshot (i.e., `<ETCD-SNAPSHOT-NAME>`).
Why is ETCD capitalised in some places while it is etcd is the remaining? pls verify and update accordingly.

2024-02-01 16:31 UTC, SwatiPeriwal requested changes
Pls review and update as needed..

2024-02-02 05:58 UTC, SwatiPeriwal approved these changes
Approving changes

2024-02-02 06:08 UTC, ckm007 approved these changes

2024-02-02 06:08 UTC, merged